language: php

notifications:
  email: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - TEST_PHP_ARGS="-q"
    - REPORT_EXIT_STATUS=1

before_script:
  - cd extension
  - phpize
  - ./configure
  - make clean
  - make

script:
  - ../travis/run-test.sh
